### ISSUE TITLE
groups post error

### ISSUE THREAD

**Issue by cowkong** [Damezuma/gym_solution_server#5]
![response2](https://user-images.githubusercontent.com/34023662/38347752-59e63170-38d8-11e8-9098-d47d12df2cdf.PNG)
![default](https://user-images.githubusercontent.com/34023662/38347753-5a1c4f62-38d8-11e8-9bcb-ca100a46331c.PNG)
![response](https://user-images.githubusercontent.com/34023662/38347754-5a4768d2-38d8-11e8-990e-542b1ab1929b.PNG)

**Comment by Damezuma** [comment]
해결함
